
export enum TokenType {
    /**
     * Un-assigned token enums:
        IF, ELSE, RETURN, CONTINUE, WHILE, FOR, BREAK, SWITCH, CASE, DEFAULT, 
        VAR,  INT8, INT16, INT, INT32, INT64, UINT8, UINT16, UINT, UINT32, UINT64,
        BOOL, CHAR, STRING, BYTE, FLOAT32, FLOAT64,

        IMPORT,
        CLASS, STRUCT, FUNCTION, METHOD,
        FIXED, CONST, PUBLIC, PRIVATE, PROTECTED, 
        LIST, ARRAY,

        PLUS, MINUS, MULTIPLY, DIVIDE, EXPONENT, MODULO,
        PLUS_EQUALS, MINUS_EQUALS, MULTIPLY_EQUALS, DIVIDE_EQUALS, MODULO_EQUALS,
        GT, LT, GTE, LTE, EQUALS, EQUALS_EQUALS, NOT,
        BIT_OR, BIT_AND, BIT_XOR, BIT_NOT,
        OR, AND,

        LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET, LEFT_CURLY, RIGHT_CURLY,
        SEMICOLON, COLON, DOT, COMMENT, MULTI_COMMENT_START, MULTI_COMMENT_END,
        IDENTIFIER, 
     */
    IF, ELSE, RETURN, CONTINUE, WHILE, FOR, BREAK, SWITCH, CASE, DEFAULT, 
    VAR,  INT8, INT16, INT, INT32, INT64, UINT8, UINT16, UINT, UINT32, UINT64,
    BOOL, CHAR, STRING, BYTE, FLOAT32, FLOAT64,

    IMPORT,
    CLASS, STRUCT, FUNCTION, METHOD,
    FIXED, CONST, PUBLIC, PRIVATE, PROTECTED, 
    LIST, ARRAY,

    PLUS, MINUS, MULTIPLY, DIVIDE, EXPONENT, MODULO,
    PLUS_EQUALS, MINUS_EQUALS, MULTIPLY_EQUALS, DIVIDE_EQUALS, MODULO_EQUALS,
    GT, LT, GTE, LTE, EQUALS, EQUALS_EQUALS, NOT,
    BIT_OR, BIT_AND, BIT_XOR, BIT_NOT,
    OR, AND,

    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET, LEFT_CURLY, RIGHT_CURLY,
    SEMICOLON, COLON, DOT, COMMENT, MULTI_COMMENT_START, MULTI_COMMENT_END,
    IDENTIFIER,

    // For lexing/parsing purposes:
    COMPILER_NOT_SET,
}

export class Token {
    token_line: number
    token_value: string
    token_type: TokenType

    constructor() {
        this.token_line = -1
        this.token_value = ""
        this.token_type = TokenType.COMPILER_NOT_SET
    }
}